name: keepsafe
description: A secure app to store confidential information.
version: 1.2.1+6

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI components
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  
  # State management
  provider: ^6.0.5
  
  # Local storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  
  # Security
  flutter_secure_storage: ^8.0.0
  encrypt: ^5.0.1
  local_auth: ^2.1.7
  package_info_plus: ^8.3.0
  
  # Search and filtering
  fuzzy: ^0.4.0-nullsafety.0
  
  # Image handling
  image_picker: ^1.0.4
  path: ^1.8.3
  
  # File operations and sharing
  file_picker: ^10.1.9
  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  crypto: ^3.0.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/ 

# Launcher icon configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.jpeg"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.jpeg" 